### ISSUE TITLE
Platform Metrics deployment is failing

### ISSUE THREAD

**Issue by ireneisdoomed** [opentargets/issues#2559]
**Describe the bug**
The app to explore and visualise the metrics (https://share.streamlit.io/opentargets/ot-release-metrics/app.py) is not working after an update. 

**Observed behaviour**
Metrics pre 22.04 pipeline run were generated and pushed to the metrics repo (https://github.com/opentargets/ot-release-metrics/blob/master/data/22.04.1-pre.csv)

The app is automatically redeployed after every change in the master branch. However, deployment is failing and from the trace back it looks like it is something internal to Streamlit.

I've tried rebooting the app and the error is the same:

```

Traceback (most recent call last):
  File "/home/appuser/venv/bin/streamlit", line 8, in <module>
    sys.exit(main())
  File "/home/appuser/venv/lib/python3.7/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/appuser/venv/lib/python3.7/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/appuser/venv/lib/python3.7/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/appuser/venv/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/appuser/venv/lib/python3.7/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/appuser/venv/lib/python3.7/site-packages/streamlit/cli.py", line 202, in main_run
    _main_run(target, args, flag_options=kwargs)
  File "/home/appuser/venv/lib/python3.7/site-packages/streamlit/cli.py", line 230, in _main_run
    command_line = _get_command_line_as_string()
  File "/home/appuser/venv/lib/python3.7/site-packages/streamlit/cli.py", line 219, in _get_command_line_as_string
    cmd_line_as_list.extend(click.get_os_args())
AttributeError: module 'click' has no attribute 'get_os_args'
```

I don't think we've changed anything that affects the app configuration but we'll have to investigate. 
Full log:
[logs-opentargets-ot-release-metrics-master-app.py-2022-04-13T09_26_18.578Z.txt](https://github.com/opentargets/issues/files/8480157/logs-opentargets-ot-release-metrics-master-app.py-2022-04-13T09_26_18.578Z.txt)

**To Reproduce**
Steps to reproduce the behaviour:
1. Log in with your GH credentials in https://share.streamlit.io
2. Go to the opentargets account to access the app settings. 
3 If you reboot it you will be able to see the full log. 

**Additional context**
Metrics can still be accessed in the file above and the app is working when running it locally with `streamlit run app.py`

**Comment by DSuveges** [comment]
I could reproduce the error on my local environment:

```
Traceback (most recent call last):
  File "/Users/dsuveges/repositories/ot-release-metrics/env/bin/streamlit", line 8, in <module>
    sys.exit(main())
  File "/Users/dsuveges/repositories/ot-release-metrics/env/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/dsuveges/repositories/ot-release-metrics/env/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/dsuveges/repositories/ot-release-metrics/env/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/dsuveges/repositories/ot-release-metrics/env/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/dsuveges/repositories/ot-release-metrics/env/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/dsuveges/repositories/ot-release-metrics/env/lib/python3.9/site-packages/streamlit/cli.py", line 207, in main_run
    _main_run(target, args, flag_options=kwargs)
  File "/Users/dsuveges/repositories/ot-release-metrics/env/lib/python3.9/site-packages/streamlit/cli.py", line 228, in _main_run
    command_line = _get_command_line_as_string()
  File "/Users/dsuveges/repositories/ot-release-metrics/env/lib/python3.9/site-packages/streamlit/cli.py", line 217, in _get_command_line_as_string
    cmd_line_as_list.extend(click.get_os_args())
AttributeError: module 'click' has no attribute 'get_os_args'
```

I noticed that the streamlit version was [recently upgraded](https://github.com/opentargets/ot-release-metrics/commit/c9e38e88b197ee80f58f375699d4513d7aeeb5cb) from 0.80.0, however, when downgrading, I got the same error. 

Apparently, the [new version of click](https://github.com/streamlit/streamlit/issues/4555) broke the existing API, but you if specify the older click version, it works:

```bash
pip install -U click==8
```

I pushed a commit with the updated requirements file and it works now.
