### ISSUE TITLE
Missing Homology data for 'sus_scrofa_usmarc'

### ISSUE THREAD

**Issue by mbdebian** [opentargets/issues#2915]
## Describe the bug
When PIS collects the homology data from the URL
```
https://ftp.ensembl.org/pub/release-{release}/tsv/ensembl-compara/homologies
```

For the species of interest, as listed in the configuration file:
```yaml
  resources:
      - 'caenorhabditis_elegans'
      - 'canis_lupus_familiaris'
      - 'cavia_porcellus'
      - 'danio_rerio'
      - 'drosophila_melanogaster'
      - 'macaca_mulatta'
      - 'mus_musculus'
      - 'oryctolagus_cuniculus'
      - 'pan_troglodytes'
      - 'rattus_norvegicus'
      - 'sus_scrofa'
      - 'sus_scrofa_usmarc'
      - 'xenopus_tropicalis'
      - 'homo_sapiens'
```

The files for *sus_scrofa_usmarc* don't contain any data, just an HTML error page.

## Observed behaviour
PIS runs the homology data collection at step _Homologues_, the following code iterates through all the species of interest:
```python
    def download_homology_data(self, conf, output) -> List[ManifestResource]:
        """
        Download the homology data for the species of interest.

        Files look like:
            Compara.<release>.[type]_default.homologies.tsv.gz -> <type>-<species>.tsv.gz
        where <species> is the species of interest and <type> is one of the specified in conf.types_homologues
        :param conf: configuration object
        :param output: information on where the output result should be place
        """
        output_folder = os.path.join(output.prod_dir,
                                     conf.path, str(conf.path_homologues))
        create_folder(output_folder)
        download_service = DownloadResource(output_folder)
        ensembl_base_uri = conf.uri_homologues.replace("{release}", str(conf.release))
        homology_data_manifests = []
        # Iterate over the species of interest to download the homology data, which is a pair of files like
        for species in conf.resources:
            self._logger.debug(f'Downloading homology files for {species}')
            for type in conf.types_homologues:
                homology_data_manifests.append(
                    self.download_homologies_for_species(
                        ensembl_base_uri, conf.release, output_folder, type, species, download_service)
                )
        return homology_data_manifests
```

For each species of interest, this code snipped downloads the pair of homology files we are interested on:
```python
    def download_homologies_for_species(uri_homologues: str, release, output, type: str, species: str,
                                        download) -> ManifestResource:
        """
        Download homology data for the given species and type.

        :param uri_homologues: base URI to the homology data
        :param release: Ensembl release number
        :param output: output directory information
        :param type: type of homology data to download
        :param species: species to download homology data for
        :param download: download service
        """
        # Create the resource info.
        download_resource = Dict()
        download_resource.uri = f"{uri_homologues}/{species}/Compara.{release}.{type}_default.homologies.tsv.gz"
        download_resource.output_filename = f'{type}-{species}.tsv.gz'
        download_resource.output_dir = output
        return download.ftp_download(download_resource)
```

The **problem** is that *sus_scrofa_usmarc* has **no _default_** homology files, as the following FTP listing shows:
```
lftp ftp.ensembl.org:/pub/release-108/tsv/ensembl-compara/homologies/sus_scrofa_usmarc> ls -alh
drwxr-xr-x  --  ..
-rw-r--r--   7.2M&nbsp;  2022-08-16 20:28  Compara.108.ncrna_pig_breeds.homologies.tsv.gz
-rw-r--r--   6.0M&nbsp;  2022-08-16 20:44  Compara.108.protein_pig_breeds.homologies.tsv.gz
```

It is very likely that we are not handling the error response correctly in the helper [method](https://github.com/opentargets/platform-input-support/blob/8b4b009217909ac4ebb0655811048bfcf95961b6/modules/common/DownloadResource.py#L117) that we use for downloading files from FTP or HTTP locations.

_urllib_ seems to throw an **HTTPError** exception when trying to reproduce the situation interactivelly using the same PIS Python environment, although instead of _404_, it appears to be a _400_

```python
>>> import urllib.request
>>> urllib.request.urlretrieve(url, "temporary.tmp")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Caskroom/miniconda/base/envs/otpis/lib/python3.8/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/local/Caskroom/miniconda/base/envs/otpis/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Caskroom/miniconda/base/envs/otpis/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/local/Caskroom/miniconda/base/envs/otpis/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/local/Caskroom/miniconda/base/envs/otpis/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/local/Caskroom/miniconda/base/envs/otpis/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/local/Caskroom/miniconda/base/envs/otpis/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request
```

We need to find out why this is not caught by the ftp downloader helper code snippet
```python
            try:
                urllib.request.urlretrieve(resource_info.uri, filename)
            except Exception as e:
                errors.append(f"FAILED Attempt #{attempt + 1} to download '{resource_info.uri}', reason '{e}'")
                logger.warning(errors[-1])
            else:
                downloaded_resource.status_completion = ManifestStatus.COMPLETED
                downloaded_resource.msg_completion = f"Download completed after {attempt + 1} attempt(s)"
                break
            finally:
                urllib.request.urlcleanup()
```

## Expected behaviour
Once the error detection when using _urllib_ has been fixed, we need to decide what to do for those cases where there are no _default_ homology files.

## To Reproduce
Run PIS for _Homologues_ step and, within the output folder ```prod/target-inputs/homologue/homologies```, you'll find the following files:
```shell
.                                      ncrna-oryctolagus_cuniculus.tsv.gz     protein-drosophila_melanogaster.tsv.gz
..                                     ncrna-pan_troglodytes.tsv.gz           protein-homo_sapiens.tsv.gz
ncrna-caenorhabditis_elegans.tsv.gz    ncrna-rattus_norvegicus.tsv.gz         protein-macaca_mulatta.tsv.gz
ncrna-canis_lupus_familiaris.tsv.gz    ncrna-sus_scrofa.tsv.gz                protein-mus_musculus.tsv.gz
ncrna-cavia_porcellus.tsv.gz           ncrna-sus_scrofa_usmarc.tsv.gz         protein-oryctolagus_cuniculus.tsv.gz
ncrna-danio_rerio.tsv.gz               ncrna-xenopus_tropicalis.tsv.gz        protein-pan_troglodytes.tsv.gz
ncrna-drosophila_melanogaster.tsv.gz   protein-caenorhabditis_elegans.tsv.gz  protein-rattus_norvegicus.tsv.gz
ncrna-homo_sapiens.tsv.gz              protein-canis_lupus_familiaris.tsv.gz  protein-sus_scrofa.tsv.gz
ncrna-macaca_mulatta.tsv.gz            protein-cavia_porcellus.tsv.gz         protein-sus_scrofa_usmarc.tsv.gz
ncrna-mus_musculus.tsv.gz              protein-danio_rerio.tsv.gz             protein-xenopus_tropicalis.tsv.gz
```

The files produced for *sus_scrofa_usmarc* are **not valid**.

**Comment by mbdebian** [comment]
@d0choa , should we ignore those species without _default_ homology files?

**Comment by d0choa** [comment]
use this instead: 
https://ftp.ensembl.org/pub/release-109/tsv/ensembl-compara/homologies/sus_scrofa/
