### ISSUE TITLE
FTP connection error

### ISSUE THREAD

**Issue by antivirak** [opentargets/issues#2924]
**Describe the bug**
Hello, I have problems accessing the datasets on ftp.ebi.ac.uk via FTP (port 21). I do not have problems accessing it via https in my browser.

**Observed behaviour**
I'm getting "ConnectionResetError: [Errno 54] Connection reset by peer" error

**Expected behaviour**
I expect to connect and download the datasets via FTP as it worked for me before.

**To Reproduce**
Steps to reproduce the behaviour:
E.g. in python3:
```
from ftplib import FTP

with FTP('ftp.ebi.ac.uk') as ftp:
    ftp.login()

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ftplib.py", line 121, in __init__
    self.connect(host)
  File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ftplib.py", line 162, in connect
    self.welcome = self.getresp()
                   ^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ftplib.py", line 244, in getresp
    resp = self.getmultiline()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ftplib.py", line 230, in getmultiline
    line = self.getline()
           ^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ftplib.py", line 212, in getline
    line = self.file.readline(self.maxline + 1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/socket.py", line 706, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 54] Connection reset by peer
```
**Additional context**
None

**Comment by prashantuniyal02** [comment]
Hi @antivirak, we are looking into the error. 
We have a growing [community of open targets users](https://community.opentargets.org/c/data-access/11) where you can post your queries and find answers to technical support questions about accessing Open Targets data. It would be great if you could kindly repost your query on the community page to get a quicker response from the community members.

**Comment by antivirak** [comment]
Thanks, got the answer there:
"Thank you for flagging this. This is an issue with the EBI FTP service, rather than the Open Targets datasets in particular. The EBI FTP service is experiencing some intermittent issues, and their technical services team is aware."
