### ISSUE TITLE
Command Line Interface for gentropy steps

### ISSUE THREAD

**Issue by project-defiant** [opentargets/issues#3408]
As a **user** I want **be able to run gentropy commands after it's installation from pipy by command line interface. Moreover I want to be able to run full gwas catalog processing steps as a single pipeline** because **it will make it easier to run the gentropy steps in orchestration layer.**

## Background

The issues arise when one want to create a DAG with a big number of conditional logic. In that context it is easier to wrap multiple gentropy steps with some combination logic in between them. For instance - adding the QC branching to trigger different fine mapping step execution.

The overall concept to to create a CLI command that will wrap the existing gentropy steps that are required to run in `gwas_catalog_harmonisation`, `gwas_catalog_curation` and `gwas_catalog_processing` dags, so the command may be pushed as a single google batch task. 

Things to consider:
- how to report if one of the steps has failed
- how to keep the state of the pipeline execution (in case of a failure in one of the tasks we should be able to force restart whole job or just continue, provided we changed the machine type for the batch execution)
- how to preserve the non-specificity of the separate steps when we can not overwrite hydra configuration (move away from hydra to a native CLI library)

These are a few libraries that might be used
- [click](https://click.palletsprojects.com/en/8.1.x/)
- [typer](https://typer.tiangolo.com/)
- [cyclops](https://cyclopts.readthedocs.io/en/latest/)

The advantage over the hydra:
- cli has the help message with all possible flags and required arguments
- cli can be structured by the commands
- No error is thrown on missing arguments, just a nice message explaining what is missing

The overrige syntax for the non-specific options can be provided as group options (for instance the spark sessions extended config)

## Tasks

- [ ] Create a step that wraps the gwas catalog processing steps into a single executable (if feasable)
- [ ] Experiment and decide which cli tool may be a better solution to the native command line

## Acceptance tests

How do we know the task is complete? 

1. When gentropy steps can be run without need to overwrite the configuration steps

**Comment by project-defiant** [comment]
This issue is most likely out of scope for now. We could benefit for other CLI library, but that will be a sibstantial refactoring of the gentropy and orchestration configurations. The main issues I can find right now with the current CLi are:

1. Run gentropy with the step specified without the `step=variant_index` flag should not result in the cryptic error as below. This should clearly state that the reaseon of failure is not providing the flag in a correct way.
```
(base) ☁  gentropy [dev] poetry run gentropy variant_index
Error parsing override 'variant_index'
missing EQUAL at '<EOF>'
See https://hydra.cc/docs/1.2/advanced/override_grammar/basic for details

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

```

2. Running without proper parameter setup also results in error that may not be understand if the user did not use hydra before. The exact issue is buried inside the stack trace, - `Missing mandatory value: step.vep_output_json_path` this should be exposed as an issue that user faces directly.
```
(base) ☁  gentropy [dev] poetry run gentropy step=variant_index
step:
  session:
    start_hail: false
    write_mode: errorifexists
    spark_uri: local[*]
    hail_home: /Users/ss60/Public/projects/gentropy/.venv/lib/python3.10/site-packages/hail
    extended_spark_conf: {}
    _target_: gentropy.common.session.Session
  vep_output_json_path: ???
  variant_index_path: ???
  gnomad_variant_annotations_path: null
  hash_threshold: 300
  _target_: gentropy.variant_index.VariantIndexStep
datasets: {}

Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
24/09/24 09:35:19 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Error executing job with overrides: ['step=variant_index']
Traceback (most recent call last):
  File "/Users/ss60/Public/projects/gentropy/src/gentropy/cli.py", line 22, in main
    instantiate(cfg.step)
  File "/Users/ss60/Public/projects/gentropy/.venv/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 226, in instantiate
    return instantiate_node(
  File "/Users/ss60/Public/projects/gentropy/.venv/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 340, in instantiate_node
    value = node[key]
omegaconf.errors.MissingMandatoryValue: Missing mandatory value: step.vep_output_json_path
    full_key: step.vep_output_json_path
    reference_type=StepConfig
    object_type=VariantIndexConfig

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
[2024-09-24 09:35:22,618][py4j.clientserver][INFO] - Closing down clientserver connection
```

The other minor thing is that, without consulting the [documentation](https://opentargets.github.io/gentropy/python_api/steps/_steps/) we do not get clear view on what parameters should be passed to the step directly and in what way they should be passed as well. This could be a typical example `how to run the step` that displays when the `gentropy --help` is provided as a parameter. Insead we are getting

```
(base) ☁  gentropy [dev] poetry run gentropy --help
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/ss60/Public/projects/gentropy/.venv/lib/python3.10/site-packages/hydra/main.py", line 94, in decorated_main
    _run_hydra(
  File "/Users/ss60/Public/projects/gentropy/.venv/lib/python3.10/site-packages/hydra/_internal/utils.py", line 363, in _run_hydra
    hydra.app_help(config_name=config_name, args_parser=args_parser, args=args)
  File "/Users/ss60/Public/projects/gentropy/.venv/lib/python3.10/site-packages/hydra/_internal/hydra.py", line 356, in app_help
    cfg = self.compose_config(
  File "/Users/ss60/Public/projects/gentropy/.venv/lib/python3.10/site-packages/hydra/_internal/hydra.py", line 594, in compose_config
    cfg = self.config_loader.load_configuration(
  File "/Users/ss60/Public/projects/gentropy/.venv/lib/python3.10/site-packages/hydra/_internal/config_loader_impl.py", line 142, in load_configuration
    return self._load_configuration_impl(
  File "/Users/ss60/Public/projects/gentropy/.venv/lib/python3.10/site-packages/hydra/_internal/config_loader_impl.py", line 253, in _load_configuration_impl
    defaults_list = create_defaults_list(
  File "/Users/ss60/Public/projects/gentropy/.venv/lib/python3.10/site-packages/hydra/_internal/defaults_list.py", line 745, in create_defaults_list
    defaults, tree = _create_defaults_list(
  File "/Users/ss60/Public/projects/gentropy/.venv/lib/python3.10/site-packages/hydra/_internal/defaults_list.py", line 715, in _create_defaults_list
    defaults_tree = _create_defaults_tree(
  File "/Users/ss60/Public/projects/gentropy/.venv/lib/python3.10/site-packages/hydra/_internal/defaults_list.py", line 356, in _create_defaults_tree
    ret = _create_defaults_tree_impl(
  File "/Users/ss60/Public/projects/gentropy/.venv/lib/python3.10/site-packages/hydra/_internal/defaults_list.py", line 457, in _create_defaults_tree_impl
    return _expand_virtual_root(repo, root, overrides, skip_missing)
  File "/Users/ss60/Public/projects/gentropy/.venv/lib/python3.10/site-packages/hydra/_internal/defaults_list.py", line 280, in _expand_virtual_root
    subtree = _create_defaults_tree_impl(
  File "/Users/ss60/Public/projects/gentropy/.venv/lib/python3.10/site-packages/hydra/_internal/defaults_list.py", line 573, in _create_defaults_tree_impl
    add_child(children, new_root)
  File "/Users/ss60/Public/projects/gentropy/.venv/lib/python3.10/site-packages/hydra/_internal/defaults_list.py", line 520, in add_child
    subtree_ = _create_defaults_tree_impl(
  File "/Users/ss60/Public/projects/gentropy/.venv/lib/python3.10/site-packages/hydra/_internal/defaults_list.py", line 477, in _create_defaults_tree_impl
    if _check_not_missing(repo=repo, default=parent, skip_missing=skip_missing):
  File "/Users/ss60/Public/projects/gentropy/.venv/lib/python3.10/site-packages/hydra/_internal/defaults_list.py", line 322, in _check_not_missing
    raise ConfigCompositionException(msg + opt_list)
hydra.errors.ConfigCompositionException: You must specify 'step', e.g, step=<OPTION>
Available options:
	colocalisation
	credible_set_validation
	eqtl_catalogue
	finngen_finemapping_ingestion
	finngen_studies
	finngen_ukb_meta_ingestion
	gene_index
	gnomad_variants
	gwas_catalog_ingestion
	gwas_catalog_study_curation
	gwas_catalog_study_inclusion
	gwas_catalog_sumstat_preprocess
	ld_based_clumping
	ld_index
	locus_breaker_clumping
	locus_to_gene
	pics
	study_validation
	summary_statistics_qc
	susie_finemapping
	ukb_ppp_eur_sumstat_preprocess
	variant_index
	variant_to_gene
	variant_to_vcf
	window_based_clumping
```

I had some checks on how to allow a bit more verbose command line with Hydra, the issue I have bumped into is that we `specifically` require to pass the `step=xxx` flag, otherwise the command will allways fail with stacktrace.
I would like to park this issue, as it is not crucial for the upcomming release. 

Development and testing done under [branch](https://github.com/opentargets/gentropy/tree/3408-command-line-interface-for-gentropy-steps)

@d0choa what do you think?

**Comment by d0choa** [comment]
I agree. I think pushing `hydra` to resolve the CLI task is not the best idea. Now it's not the best time to perform this refactor, but it's a nice one to come back once everything else is a bit more clear.

The intention is already a `Won't` for December. I think it could also be ok to close the ticket as it doesn't add a massive context apart from "we want to change this." We could open a better ticket when the time comes
